x-environment-defaults: &environment-defaults
  DEBUG: "True"
  DJANGO_DATABASE_NAME: "Netflix"
  DJANGO_DATABASE_USER: "postgres"
  DJANGO_DATABASE_PASSWORD: "Hayk1234"
  DJANGO_DATABASE_HOST: "postgres"
  DJANGO_DATABASE_PORT: 5432
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SECRET_KEY: "django-insecure-954j6g&=p37(40r$)0pt%t2xfh7a)h^0heyj9&_gs6w6brm_hq"
  VITE_PROTOCOL: 'https://'
  VITE_IP: '192.168.1.213:8000'
  VITE_URL: 'https://192.168.1.213:8000/'
  VITE_GOOGLE_CLIENT_ID: '97173424287-mr88917mp74110bl0so2a4un1gmorq0h.apps.googleusercontent.com'


services:
  frontend:
    container_name: frontend
    build:
      context: ./film
    ports:
      - "3000:3001"
    networks:
      - netflix-network
    environment:
      <<: *environment-defaults

  backend:
    container_name: backend
    build:
      context: ./django
    volumes:
      - ./django:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    networks:
      - netflix-network
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    restart: on-failure:1

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: Netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hayk1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - netflix-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - netflix-network

  celery:
    container_name: celery_worker
    build:
      context: ./django
    command: celery -A Film worker --loglevel=INFO
    volumes:
      - ./django:/app
    depends_on:
      - redis
      - postgres
    networks:
      - netflix-network
    environment:
      <<: *environment-defaults

  celery-beat:
    container_name: celery_beat
    build:
      context: ./django
    command: celery -A Film beat --loglevel=INFO
    depends_on:
      - backend
      - redis
      - postgres
    volumes:
      - ./django:/app
    networks:
      - netflix-network
    restart: on-failure:1
    environment:
      <<: *environment-defaults

volumes:
  pg_data:
  static_volume:

networks:
  netflix-network:
    driver: bridge