# Generated by Django 5.1.3 on 2024-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingletoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_URL', models.URLField(verbose_name='front_URL')),
            ],
            options={
                'verbose_name': 'Singletone',
                'verbose_name_plural': 'Singletone',
            },
        ),
    ]
