# Generated by Django 5.1.3 on 2024-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film',
            field=models.ManyToManyField(related_name='Film', to='main.film'),
        ),
    ]
