# Generated by Django 5.1.3 on 2024-12-06 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_rate_rate_rated_film_rate_alter_rate_film_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('film', 'user'), name='unique_pair'),
        ),
    ]
