# Generated by Django 5.1.3 on 2024-11-30 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
