# Generated by Django 5.1.3 on 2024-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(editable=False, verbose_name='Verification code'),
        ),
    ]
