# Generated by Django 5.1.3 on 2024-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Verification code'),
        ),
    ]
