# Generated by Django 5.1.3 on 2024-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trycount',
            field=models.IntegerField(default=0, verbose_name='verification code tryed'),
        ),
    ]
